name: Run app with Xvfb

on:
  push:
    branches: [ "relese" ]
  pull_request:
    branches: [ "relese" ]

jobs:
  run-with-xvfb:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies and Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run app with virtual display (Xvfb)
      run: |
        xvfb-run -a python main.pyw
